### ISSUE TITLE
Run.bat errors

### ISSUE THREAD

**Issue by trappuss** [polivilas/EmuTarkov#34]
EmuTarkov used to work just fine for me but not sure why I keep getting this error when I open "Run". Yes I did run install first.

**events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::1337
    at Server.setupListenHandle [as _listen2] (net.js:1279:14)
    at listenInCluster (net.js:1327:12)
    at Server.listen (net.js:1414:7)
    at Object.start (C:\Games\EmuTarkov-master\src\server.js:63:9)
    at Object.<anonymous> (C:\Games\EmuTarkov-master\src\main.js:16:9)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Emitted 'error' event at:
    at emitErrorNT (net.js:1306:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Press any key to continue . . .**

**Comment by trappuss** [comment]
also when I run my OLDest installed version of EmuTarkov I instead get this error


**events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::1337
    at Server.setupListenHandle [as _listen2] (net.js:1279:14)
    at listenInCluster (net.js:1327:12)
    at Server.listen (net.js:1414:7)
    at Object.start (C:\Users\notso\OneDrive\Desktop\Emu\EmuTarkov-master\src\server.js:63:9)
    at Object.<anonymous> (C:\Users\notso\OneDrive\Desktop\Emu\EmuTarkov-master\src\main.js:16:9)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Emitted 'error' event at:
    at emitErrorNT (net.js:1306:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Press any key to continue . . .**

**Comment by polivilas** [comment]
You already got some server running on port 1337 - Either turn it off, or change port in config, both in EmuTarkov and EFT itself.
