### ISSUE TITLE
help installing it.

### ISSUE THREAD

**Issue by jagr0399** [polivilas/EmuTarkov#36]
hi guys i need help installing this version i followed all the steps and everything but everytime i press install it closes on itself and when i press run and run tarkov it wont even launch.

**Comment by themaoci** [comment]
check newest release you will propably like it ;)
and search for "justemutarkov"

**Comment by polivilas** [comment]
Please run `npm install` and `node server.js` in main folder and respond with results. You either A) don't have node B) something else is running on port 1337.

**Comment by spiritov0d** [comment]
Some points in the new launcher are not that obvious, so you probably should add more info somewhere in readme or FAQ:
1) Game location and server location paths should be like this:
C:\My Games\Escape from Tarkov\\
C:\My Games\Escape from Tarkov\unpacked server\\
with backslash at the end and without quotation marks.
2) Email should be only user0@emutarkov.com or user1@emutarkov.com or you'll get "account not found" error after loading the game - because those are only two existing pre-defined profiles.

**Comment by jagr0399** [comment]
Error: Cannot find module 'regedit'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (F:\EFT\src\launcher.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)

this is the error i get

**Comment by jagr0399** [comment]
EFT>npm install
audited 12 packages in 0.537s
found 0 vulnerabilities
then i get this when i run as admin

**Comment by jagr0399** [comment]
SyntaxError: Unexpected token h in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (F:\EFT\src\settings.js:5:17)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (F:\EFT\src\server.js:6:18)
Press any key to continue . . . i get this error when i put the emutarkov launcher and server in the same eft file

**Comment by jagr0399** [comment]
but now i get this error npm WARN saveError ENOENT: no such file or directory, open 'F:\EFT\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'F:\EFT\package.json'
npm WARN EFT No description
npm WARN EFT No repository field.
npm WARN EFT No README data
npm WARN EFT No license field.

audited 34 packages in 0.44s
found 0 vulnerabilities

**Comment by jagr0399** [comment]
if anyone can add my discord and help me my discord is jagr034#8267.

**Comment by jagr0399** [comment]
and whenever i run the eft launcher it tells me its listening to port:1337 what does that mean

**Comment by themaoci** [comment]
that it listen the port 1337
localhost:1337
192.168.1.<yournumber>:1337

**Comment by jagr0399** [comment]
> that it listen the port 1337
> localhost:1337
> 192.168.1.:1337

ok but when i launch the launcher it just pops a command prompt and just say listening to port 1337. what do i do?
