### ISSUE TITLE
Discord?

### ISSUE THREAD

**Issue by sc20ka** [polivilas/EmuTarkov#37]
did u have discord group to discuss this server :D ?
or can u add me, wanna some many questions sc20ka#7982

and i have some error after many manipulating with items in inventory in menu

/client/ragfair/search with data  {"page":0,"limit":15,"sortType":5,"sortDirection":0,"currency":0,"priceFrom":0,"priceTo":0,"quantityFrom":0,"quantityTo":0,"conditionFrom":0,"conditionTo":100,"oneHourExpiration":false,"onlyPrioritized":false,"removeBartering":false,"removeMerchantOffers":false,"onlyFunctional":true,"updateOfferCount":false,"handbookId":"5b4329f05acfc47a86086aa1","linkedSearchId":"","neededSearchId":"","tm":1}
found item
C:\Games\Escape from Tarkov\JustEmutarkov\src\ragfair.js:62
                        response.data.offers.push(CreateOffer(tmpId));
                                             ^

ReferenceError: CreateOffer is not defined
    at Object.getOffers (C:\Games\Escape from Tarkov\JustEmutarkov\src\ragfair.js:62:25)
    at Object.get (C:\Games\Escape from Tarkov\JustEmutarkov\src\response.js:252:21)
    at sendResponse (C:\Games\Escape from Tarkov\JustEmutarkov\src\server.js:32:21)
    at Inflate.cb (C:\Games\Escape from Tarkov\JustEmutarkov\src\server.js:61:5)
    at Inflate.zlibBufferOnEnd (zlib.js:123:10)
    at Inflate.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by themaoci** [comment]
JustEmuTarkov - ~Discord https://discord.gg/mpB9Utz~ info: New community holded by TheMaoci - Rules are bound mostly to discord rules, if you dont break them you are fine.
    EmuTarkov - ~Discord https://discord.gg/BpKdMkv~ info: English Community holded by old veterans of EmuTarkov
    JRT - ~Discord https://discord.com/invite/7JhZHcP~ Info: Russian discord community holded by old Russian veterans of EmuTarkov
    ConfigFreaks - ~Discord https://discord.com/CeBQqzB~ info: Community of modders
    Senko's Pub - ~Guilded https://www.guilded.gg/senkospub~ info: InNoHurryToCode Community - Watchout on words there or you will be kicked or banned (admin's there can be narcissistic).
