### ISSUE TITLE
Found error when buying and exchanging anything from all traders 

### ISSUE THREAD

**Issue by ghost** [polivilas/EmuTarkov#42]
Items taken. Status OK.
Bought item: 5cacc36288a4500dd046cc07
SERVER CRASHED! - check lastest .log file
[ERROR] - starts
TypeError: Cannot read property 'fill' of undefined
    at recheckInventoryFreeSpace (C:\Users\WGuifei\Desktop\EmuTarkov-master\Server\Server\project\src\item.js:31:34)
    at buyItem (C:\Users\WGuifei\Desktop\EmuTarkov-master\Server\Server\project\src\item.js:619:22)
    at confirmTrading (C:\Users\WGuifei\Desktop\EmuTarkov-master\Server\Server\project\src\item.js:735:10)
    at handleMoving (C:\Users\WGuifei\Desktop\EmuTarkov-master\Server\Server\project\src\item.js:838:11)
    at Object.moving (C:\Users\WGuifei\Desktop\EmuTarkov-master\Server\Server\project\src\item.js:854:12)
    at Object.get (C:\Users\WGuifei\Desktop\EmuTarkov-master\Server\Server\project\src\response.js:107:18)
    at sendResponse (C:\Users\WGuifei\Desktop\EmuTarkov-master\Server\Server\project\src\server.js:177:22)
    at Inflate.cb (C:\Users\WGuifei\Desktop\EmuTarkov-master\Server\Server\project\src\server.js:244:6)
    at Inflate.zlibBufferOnEnd (zlib.js:131:10)
    at Inflate.emit (events.js:203:15)
[ERROR] - ends
[KILLING PROCESS]

Need anything else?

**Comment by polivilas** [comment]
Hello,
This seems to be a JustEmuTarkov fork - you should head over there instead.
https://github.com/justemutarkov/EmuTarkov-Server
